# # Install necessary package
# pip install demogpt
#
# # Export OpenAI API Key
# export OPENAI_API_KEY=[your api key]
#
# # Clone the DemoGPT repository
# git clone https://github.com/melih-unsal/DemoGPT.git
#
# # Change directory to the cloned repository
# cd DemoGPT
#
# # Install the DemoGPT package
# pip install .

# Import the DemoGPT class from the demogpt package
from demogpt import DemoGPT

# Initialize the DemoGPT agent with the specified model name
# If OPENAI_API_KEY is not set in environment variables, pass it with openai_api_key argument
agent = DemoGPT(model_name="gpt-3.5-turbo")

# Define the instruction and title for the agent
instruction = "Your instruction here"
title = "Your title here"

# Initialize an empty string to hold the final code
code = ""

# Iterate over the phases generated by the agent
for phase in agent(instruction=instruction, title=title):
    print(phase)  # Print the resulting JSON for each generation stage
    if phase["done"]:
        code = phase["code"]  # Store the final code

# Print the final code
print(code)

# Run the Streamlit app
# streamlit run demogpt/app.py
